### ISSUE TITLE
Questionable Autovalue write string benchmark

### ISSUE THREAD

**Issue by elucash** [taichi/json-benchmarks#1]
Thank you for providing JSON benchmark featuring many technologies!
I was quite interested why auto did get such low numbers on serialization to JSON. Currently I suspect that no attributes are being serialized and JSON ends up as empty document "{}". It may happen, for example, by not having attributes annotated with `@JsonProperty`. At least it was the case with the versions of Jackson I used some time ago, my apologies if it's not the case.

Please see sample documents for autovalue benchmark [AutoDocument.java](https://github.com/immutables/samples/blob/master/json/src/org/immutables/samples/json/autojackson/AutoDocument.java).

While running Jackson benchmarks in combinations I would always include pojo (with public mutable fields) benchmark as a baseline to compare against.

**Comment by taichi** [comment]
thank you !! it's my bad.

**Comment by taichi** [comment]
fixed. report is [here](https://gist.github.com/taichi/fc83f36297742aeec4b8)
